services:
  database:
    platform: linux/amd64
    container_name: database
    restart: unless-stopped
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '4306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - crypto-dev

  crypto-php:
    platform: linux/amd64
    container_name: php
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/crypto
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - database
    networks:
      - crypto-dev

  nginx:
    platform: linux/amd64
    container_name: nginx
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/crypto
    depends_on:
      - crypto-php
    networks:
      - crypto-dev

  phpmyadmin:
    platform: linux/amd64
    container_name: pma
    image: phpmyadmin/phpmyadmin
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - '8083:80'
    depends_on:
      - database
      - crypto-php
      - nginx
    networks:
      - crypto-dev

  redis:
    platform: linux/amd64
    container_name: redis
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6380}:6379'
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
    networks:
      - crypto-dev

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local

networks:
  crypto-dev:
    driver: bridge
