name: Build, Test, and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Copy .env file
        run: cp .env.example .env

      - name: Validate docker compose file
        run: docker compose config

      - name: Build and start containers
        run: docker compose up -d --build
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}

      - name: Check Docker containers
        run: docker ps -a

      - name: Check PHP version in container
        run: docker exec php php -v

      - name: Check Composer version
        run: docker exec php composer --version

      - name: Check if Vendor Directory Exists
        run: docker exec php bash -c "if [ ! -d /var/www/crypto/vendor ]; then echo 'Vendor directory not found'; exit 1; fi"

      - name: Run Migrations
        run: docker exec php php artisan migrate:fresh --seed

      - name: Run PHPUnit tests
        run: docker exec php php artisan test

      - name: Stop Docker Containers
        run: docker compose down
